---
inventory_name: AAP Managed Inventory
inventory_vm_name: Linux Daily Demo
inventory_vm_region: us-west-1
#
# These variables are set in the vm role
# vm_name: Linux Daily Demo
# vm_region: us-west-1
#
# Set these variables in the job template extra vars
# ansible_python_interpreter: /usr/bin/python3
#
# Credential Types needed for this role
# Amazon Web Services
# Red Hat Ansible Automation Platform
