---
inventory_vm_name: Linux Daily Demo
# Use a Red Hat Ansible Automation Platform credential type
# CONTROLLER_HOST: example.com
# CONTROLLER_USERNAME: mickey.mouse
# CONTROLLER_PASSWORD: password
inventory_managed_inventory_name: AAP Managed Inventory
inventory_region: us-west-1
ansible_python_interpreter: /usr/bin/python3
